FROM alpine:3.8
MAINTAINER chishin <pro@xxgzs.org>

WORKDIR /
ENV VERSION 0.0.2
ENV PORT 9090
ENV KEY false

RUN apk update && \
    apk add ca-certificates && \
    update-ca-certificates && \
    apk --no-cache add openssl wget && \
    mkdir /web && \
    cd /web && \
    wget https://github.com/xiaoxinpro/WolGoWeb/releases/download/V${VERSION}/WolGoWeb_${VERSION}_linux_amd64 -O ./WolGoWeb && \
    # wget https://github.com/xiaoxinpro/WolGoWeb/raw/master/docker/WolGoWeb_Linux_amd64 -O ./WolGoWeb  && \
    chmod 777 /web/WolGoWeb

ENV TZ Asia/Shanghai
RUN apk add tzdata && \
    ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

VOLUME /web

EXPOSE $PORT

CMD /web/WolGoWeb -c env

